name: notebook2pdf

on:
  push:
    branches:
      - main  # Change to your default branch if different
    paths:
      - 'notebook/*.md'  # Trigger on markdown file changes
      - '.github/workflows/notebook2pdf.yml'  # Re-run if workflow changes
      - '.github/formatting/preamble.tex'  # Re-run if preamble changes
  workflow_dispatch:  # Allow manual triggering

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare file list
        id: files_list
        run: |
          # Define the markdown files in the order you want them compiled
          FILES=(
            "notebook/Introduction.md"
            "notebook/Literature.md"
            "notebook/Progress.md"
            "notebook/Thoughts.md"
          )
          
          # Format for pandoc
          echo "files=$(printf '"%s" ' "${FILES[@]}")" >> $GITHUB_OUTPUT
      - name: Convert Markdown to PDF with Pandoc Docker
        uses: docker://pandoc/latex:3.6
        with:
          args: >-
            ${{ steps.files_list.outputs.files }}
            --pdf-engine=xelatex
            -H .github/formatting/preamble.tex
            -f markdown+rebase_relative_paths
            -o notebook/Notebook.pdf
            --toc
            --number-sections
            -V geometry:margin=1in
            -V linkcolor:blue
            -V urlcolor:blue
            -V toc-depth:2
            -V secnumdepth:3
            -V title="Part III Project Notebook"
            -V author="Thomas Holland (th675)"
            -V date="October 2025 - "
            -V documentclass=article

      - name: Commit and push PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add notebook/*.pdf
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generate PDF from markdown files"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}